services:
  - type: web
    name: dashboard-ssse
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python generate_dashboard_devicelogin.py
    envVars:
      - key: EXCEL_PATH
        value: "Documents/Collaboratif -SBOULA-/Contrôle Qualité -CQT-/Controle qualité -SBOULA-/2025 CQ SBOULA/2025 CQ SBOULA FOCQT01_02.xlsx"
